#ifndef STORE_LOAD_TOKENS_HPP
#define STORE_LOAD_TOKENS_HPP

#define WORD_INSTRUCTIONS(INSTR) \
    COND_INSTR(INSTR) \
    COND_INSTR_(INSTR,B) \
    COND_INSTR_(INSTR,T) \
    COND_INSTR_(INSTR,BT)

#define HALF_WORD_INSTRUCTIONS(INSTR) \
    COND_INSTR_(INSTR,H)

#define DOUBLE_WORD_INSTRUCTIONS(INSTR) \
    COND_INSTR_(INSTR,D)

#define LOAD_OPS \
    WORD_INSTRUCTIONS(LDR) \
    HALF_WORD_INSTRUCTIONS(LDR) \
    DOUBLE_WORD_INSTRUCTIONS(LDR)
    
#define STORE_OPS \
    WORD_INSTRUCTIONS(STR) \
    HALF_WORD_INSTRUCTIONS(STR) \
    DOUBLE_WORD_INSTRUCTIONS(STR)

#define ADDRESS_INSTRUCTIONS \
    X(ADR) \
    X(ADRP) \
    X(ADRL)


#define LOAD_STORE_OPS \
    LOAD_OPS \
    ADDRESS_INSTRUCTIONS \
    STORE_OPS

#endif